spring:
  profiles:
    active: dev
---
# spring配置
spring:
  # dev环境
  profiles: dev
  rabbitmq:
    host: 140.100.135.211
    port: 5672
    username: guest
    password: guest
    #集群连接
#    addresses: 140.100.135.211:5683,140.100.135.211:5684,140.100.135.211:5685
#    username: admin
#    password: admin
#    virtual-host: myTest
    #发送端消息确认开启
    publisher-confirm-type: correlated
    #发送端消息返回开启
    publisher-returns: true
    listener:
      type: simple
      #消息ack模式。此处配置是针对消费端，是否针对rabbitmq服务器进行回执
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 1000
          initial-interval: 1000
    template:
      # 发送端重试机制
      retry:
        enabled: true
        max-attempts: 3

  # 前端thymeleaf模板配置
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    # 模板文件存放位置
    prefix: classpath:/templates/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
