spring:
  profiles:
    active: dev
---
# spring配置
spring:
  # dev环境
  config:
    activate:
      on-profile: dev
  # 前端thymeleaf模板配置
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    # 模板文件存放位置
    prefix: classpath:/templates/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
