spring:
  profiles:
    active: dev
---
# spring配置
spring:
  # dev环境
  profiles: dev
  rabbitmq:
#    host: 140.100.135.211
#    port: 5682
    #集群连接
    addresses: 140.100.135.211:5683,140.100.135.211:5684,140.100.135.211:5685
    username: admin
    password: admin
    virtual-host: myTest
    #消息确认开启
    publisher-confirm-type: correlated
    #消息返回开启
    publisher-returns: true
  #    listener:
#      direct:
#        #消息ack模式
#        acknowledge-mode: manual
#      simple:
#        acknowledge-mode: manual

  # 前端thymeleaf模板配置
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    mode: HTML
    suffix: .html
    # 模板文件存放位置
    prefix: classpath:/templates/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
